apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: nyc-taxi-tip-analysis
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "866376946262.dkr.ecr.eu-central-1.amazonaws.com/dataplatform-dev/spark:3.5-py"
  imagePullPolicy: Always
  mainApplicationFile: "s3a://dataplatform-dev-data-866376946262/scripts/nyc_taxi_tip_analysis.py"
  sparkVersion: "3.5.3"

  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 2
    onSubmissionFailureRetryInterval: 20

  sparkConf:
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
    "spark.hadoop.fs.s3a.region": "eu-central-1"
    "spark.hadoop.fs.s3a.endpoint": "s3.eu-central-1.amazonaws.com"
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://dataplatform-dev-data-866376946262/eventlogs/"
    "spark.executor.gracefulDecommission.timeout": "30s"

  driver:
    cores: 1
    coreRequest: "200m"
    memory: "512m"
    serviceAccount: spark
    nodeSelector:
      role: platform
    tolerations:
      - key: role
        operator: Equal
        value: platform
        effect: NoSchedule
    labels:
      version: "3.5.3"

  executor:
    cores: 2
    coreRequest: "1500m"
    instances: 1
    memory: "2g"
    serviceAccount: spark
    nodeSelector:
      role: spark-executor
    tolerations:
      - key: role
        operator: Equal
        value: spark-executor
        effect: NoSchedule
    terminationGracePeriodSeconds: 60
    labels:
      version: "3.5.3"
