airflow:
  executor: KubernetesExecutor

  nodeSelector:
    role: platform
  tolerations:
    - key: role
      value: platform
      effect: NoSchedule
      operator: Equal

  serviceAccount:
    create: false
    name: airflow

  ingress:
    web:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - name: airflow.gusnikola.com
          tls:
            enabled: true
            secretName: airflow-tls

  postgresql:
    enabled: true
    image:
      tag: latest
    primary:
      nodeSelector:
        role: platform
      tolerations:
        - key: role
          value: platform
          effect: NoSchedule
          operator: Equal
      persistence:
        size: 5Gi
        storageClass: gp2
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

  scheduler:
    nodeSelector:
      role: platform
    tolerations:
      - key: role
        value: platform
        effect: NoSchedule
        operator: Equal
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::866376946262:role/dataplatform-dev-airflow-irsa"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  webserver:
    nodeSelector:
      role: platform
    tolerations:
      - key: role
        value: platform
        effect: NoSchedule
        operator: Equal
    startupProbe:
      failureThreshold: 18
      periodSeconds: 10
      timeoutSeconds: 20
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  triggerer:
    nodeSelector:
      role: platform
    tolerations:
      - key: role
        value: platform
        effect: NoSchedule
        operator: Equal
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::866376946262:role/dataplatform-dev-airflow-irsa"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      storageClassName: gp2

  dags:
    gitSync:
      enabled: true
      repo: https://github.com/GusNikola/DataPlatform-Infra.git
      branch: main
      subPath: dags
      period: 60s

  logs:
    persistence:
      enabled: false

  config:
    core:
      load_examples: "False"
    kubernetes_executor:
      namespace: airflow
      delete_worker_pods: "False"
      delete_worker_pods_on_failure: "False"

  extraEnv: |
    - name: AWS_DEFAULT_REGION
      value: eu-central-1
