clusterName: dataplatform-dev
nodeRoleName: dataplatform-dev-node-role

nodePool:
  instanceTypes:
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - m5a.xlarge
    - m5a.2xlarge
    - m5a.4xlarge
  capacityTypes:
    - spot
    - on-demand
  availabilityZones:
    - eu-central-1a
    - eu-central-1b
  maxNodes: 20
  consolidateAfter: 30s
