elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  nodeSelector:
    role: system

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi

  esJavaOpts: "-Xmx1g -Xms1g"

  persistence:
    enabled: true
    size: 30Gi
    storageClass: gp2

  volumeClaimTemplate:
    storageClassName: gp2
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 30Gi
