elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  nodeSelector:
    role: platform
  tolerations:
    - key: role
      value: platform
      effect: NoSchedule
      operator: Equal

  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi

  esJavaOpts: "-Xmx512m -Xms512m"

  persistence:
    enabled: true
    size: 30Gi
    storageClass: gp2

  volumeClaimTemplate:
    storageClassName: gp2
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 30Gi
